### ISSUE TITLE
Rendering issue at GithubAnalytics(MyStreak)

### ISSUE THREAD

**Issue by Vijaykumar139** [balajig1403/balajig1403#1]
I have Identified a bug in streak  is sometimes coming and sometimes not coming when i had visited your profile.
I have checked all the alternatives but still coming in profile.

**Comment by balajig1403** [comment]
Yeah I am already faced this issue. It's not an issue in code It's happening because of the link is not supposed to render all the time. For more updates you have to check out this repo in frequent.
